"""Generator for the GMAT validation scripts.

Writes GMAT scripts (*.script) into this folder. Running each script in GMAT saves its output to
tests/fixtures/gmat/<scenario>.txt, which tests/test_gmat.py reads and compares.

    python validation/gmat/make_scripts.py

Scenarios are defined in SCENARIOS. Initial states come from urania, and the gravity constants use
GMAT_EARTH, which matches GMAT's EGM96 values (the tests use the same body).
"""

from __future__ import annotations

import math
from pathlib import Path

import astropy.units as u

from urania import Body, Orbit
from urania.environment import ExponentialAtmosphere

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
FIXTURES = ROOT / "tests" / "fixtures" / "gmat"

# GMAT EGM96.cof values: μ = 398600.4415 km³/s², R = 6378.1363 km, C̄20 = -4.84165371736e-4
GMAT_EARTH = Body(
    name="Earth (GMAT EGM96)",
    mu=398600.4415e9,
    radius=6378136.3,
    J2=4.84165371736e-4 * math.sqrt(5.0),
    rotation_rate=7.292115e-5,
    flattening=1 / 298.257223563,
    atmosphere=ExponentialAtmosphere(radius=6378136.3, flattening=1 / 298.257223563),
    source="GMAT EGM96.cof",
)

# Epoch: 2000-01-01 12:00:00 TT. Precession is zero at J2000, so GMAT's true spin axis and
# urania's fixed z axis differ only by nutation (about 17").
EPOCH_GMAT = "01 Jan 2000 12:00:00.000"

SCENARIOS = {
    "twobody": dict(
        orbit=lambda: Orbit.from_elements(GMAT_EARTH, a=8000 * u.km, ecc=0.1, inc=30 * u.deg,
                                          raan=40 * u.deg, argp=60 * u.deg, nu=0 * u.deg),
        degree=0, drag=False, hours=24,
    ),
    "j2": dict(
        orbit=lambda: Orbit.circular(GMAT_EARTH, 420 * u.km, inc=51.64 * u.deg,
                                     raan=30 * u.deg),
        degree=2, drag=False, hours=24 * 7,
    ),
    "j2_drag": dict(
        orbit=lambda: Orbit.circular(GMAT_EARTH, 400 * u.km, inc=51.64 * u.deg,
                                     raan=30 * u.deg),
        degree=2, drag=True, hours=24 * 3,
    ),
}

# Spacecraft for the drag scenario (C_D·A/m = 0.022 m²/kg)
DRAG_SAT = dict(cd=2.2, area=1.0, mass=100.0)

TEMPLATE = """% urania validation script: {name}
% Generated by validation/gmat/make_scripts.py. Do not edit by hand.

% Pin Earth's shape to the values of GMAT_EARTH (used for the drag altitude)
GMAT Earth.EquatorialRadius = {radius_km:.4f};
GMAT Earth.Flattening = {flattening:.16f};

Create Spacecraft Sat;
GMAT Sat.DateFormat = TTGregorian;
GMAT Sat.Epoch = '{epoch}';
GMAT Sat.CoordinateSystem = EarthMJ2000Eq;
GMAT Sat.DisplayStateType = Cartesian;
GMAT Sat.X = {x:.15f};
GMAT Sat.Y = {y:.15f};
GMAT Sat.Z = {z:.15f};
GMAT Sat.VX = {vx:.15f};
GMAT Sat.VY = {vy:.15f};
GMAT Sat.VZ = {vz:.15f};
GMAT Sat.DryMass = {mass};
GMAT Sat.Cd = {cd};
GMAT Sat.DragArea = {area};
GMAT Sat.SRPArea = 0;

Create ForceModel FM;
GMAT FM.CentralBody = Earth;
GMAT FM.PrimaryBodies = {{Earth}};
GMAT FM.GravityField.Earth.PotentialFile = 'EGM96.cof';
GMAT FM.GravityField.Earth.Degree = {degree};
GMAT FM.GravityField.Earth.Order = 0;
GMAT FM.GravityField.Earth.TideModel = 'None';
GMAT FM.Drag.AtmosphereModel = {atmosphere};{atmosphere_file}
GMAT FM.SRP = Off;
GMAT FM.RelativisticCorrection = Off;

Create Propagator Prop;
GMAT Prop.FM = FM;
GMAT Prop.Type = RungeKutta89;
GMAT Prop.InitialStepSize = 60;
GMAT Prop.Accuracy = 1e-13;
GMAT Prop.MinStep = 0;
GMAT Prop.MaxStep = 600;

Create ReportFile OutFile;
GMAT OutFile.Filename = '{output}';
GMAT OutFile.Precision = 16;
GMAT OutFile.WriteHeaders = true;
GMAT OutFile.LeftJustify = On;
GMAT OutFile.ZeroFill = Off;

Create Variable k;

BeginMissionSequence;
Toggle OutFile Off;
Report OutFile Sat.ElapsedSecs Sat.EarthMJ2000Eq.X Sat.EarthMJ2000Eq.Y Sat.EarthMJ2000Eq.Z Sat.EarthMJ2000Eq.VX Sat.EarthMJ2000Eq.VY Sat.EarthMJ2000Eq.VZ;
% The ElapsedSecs stop condition counts from the start of each Propagate command,
% so every pass advances exactly one hour.
For k = 1:1:{hours}
   Propagate Prop(Sat) {{Sat.ElapsedSecs = 3600}};
   Report OutFile Sat.ElapsedSecs Sat.EarthMJ2000Eq.X Sat.EarthMJ2000Eq.Y Sat.EarthMJ2000Eq.Z Sat.EarthMJ2000Eq.VX Sat.EarthMJ2000Eq.VY Sat.EarthMJ2000Eq.VZ;
EndFor;
"""


def main() -> None:
    FIXTURES.mkdir(parents=True, exist_ok=True)
    for name, sc in SCENARIOS.items():
        o = sc["orbit"]()
        x, y, z = o.r / 1e3
        vx, vy, vz = o.v / 1e3
        text = TEMPLATE.format(
            name=name, epoch=EPOCH_GMAT, x=x, y=y, z=z, vx=vx, vy=vy, vz=vz,
            degree=sc["degree"], atmosphere="Exponential" if sc["drag"] else "None",
            # Same table as urania's (Vallado table 8-4); path relative to GMAT's bin folder
            atmosphere_file=("\nGMAT FM.Drag.InputFile = "
                             "'../data/atmosphere/earth/EarthExponentialAtmosphereData.txt';"
                             if sc["drag"] else ""),
            radius_km=GMAT_EARTH.radius / 1e3, flattening=GMAT_EARTH.flattening,
            hours=sc["hours"], output=(FIXTURES / f"{name}.txt").as_posix(), **DRAG_SAT,
        )
        path = HERE / f"{name}.script"
        path.write_text(text, encoding="utf-8")
        print(f"Wrote: {path}")


if __name__ == "__main__":
    main()
