"""GMAT 대조용 스크립트 생성기.

실행하면 이 폴더에 GMAT 스크립트(*.script)를 만든다. 각 스크립트를 GMAT에서 실행하면
결과가 tests/fixtures/gmat/<시나리오>.txt 로 저장되고, tests/test_gmat.py가 이를 읽어 비교한다.

    python validation/gmat/make_scripts.py

시나리오는 SCENARIOS에 정의한다. 초기 상태는 urania로 만들고, 중력 상수는 GMAT의
EGM96 값에 맞춘 GMAT_EARTH를 쓴다 (테스트도 같은 천체를 쓴다).
"""

from __future__ import annotations

import math
from pathlib import Path

import astropy.units as u

from urania import Body, Orbit
from urania.environment import ExponentialAtmosphere

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
FIXTURES = ROOT / "tests" / "fixtures" / "gmat"

# GMAT EGM96.cof 값: μ = 398600.4415 km³/s², R = 6378.1363 km, C̄20 = -4.84165371736e-4
GMAT_EARTH = Body(
    name="Earth (GMAT EGM96)",
    mu=398600.4415e9,
    radius=6378136.3,
    J2=4.84165371736e-4 * math.sqrt(5.0),
    rotation_rate=7.292115e-5,
    atmosphere=ExponentialAtmosphere(radius=6378136.3),
    source="GMAT EGM96.cof",
)

# 기준 시각: 2000-01-01 12:00:00 TT. J2000에서는 세차가 0이라
# GMAT의 실제 자전축과 urania의 고정 z축 차이가 장동(약 17") 수준으로 작다.
EPOCH_GMAT = "01 Jan 2000 12:00:00.000"

SCENARIOS = {
    "twobody": dict(
        orbit=lambda: Orbit.from_elements(GMAT_EARTH, a=8000 * u.km, ecc=0.1, inc=30 * u.deg,
                                          raan=40 * u.deg, argp=60 * u.deg, nu=0 * u.deg),
        degree=0, drag=False, hours=24,
    ),
    "j2": dict(
        orbit=lambda: Orbit.circular(GMAT_EARTH, 420 * u.km, inc=51.64 * u.deg,
                                     raan=30 * u.deg),
        degree=2, drag=False, hours=24 * 7,
    ),
    "j2_drag": dict(
        orbit=lambda: Orbit.circular(GMAT_EARTH, 400 * u.km, inc=51.64 * u.deg,
                                     raan=30 * u.deg),
        degree=2, drag=True, hours=24 * 3,
    ),
}

# 항력 시나리오의 위성 (C_D·A/m = 0.022 m²/kg)
DRAG_SAT = dict(cd=2.2, area=1.0, mass=100.0)

TEMPLATE = """% urania validation script: {name}
% Generated by validation/gmat/make_scripts.py. Do not edit by hand.

Create Spacecraft Sat;
GMAT Sat.DateFormat = TTGregorian;
GMAT Sat.Epoch = '{epoch}';
GMAT Sat.CoordinateSystem = EarthMJ2000Eq;
GMAT Sat.DisplayStateType = Cartesian;
GMAT Sat.X = {x:.15f};
GMAT Sat.Y = {y:.15f};
GMAT Sat.Z = {z:.15f};
GMAT Sat.VX = {vx:.15f};
GMAT Sat.VY = {vy:.15f};
GMAT Sat.VZ = {vz:.15f};
GMAT Sat.DryMass = {mass};
GMAT Sat.Cd = {cd};
GMAT Sat.DragArea = {area};
GMAT Sat.SRPArea = 0;

Create ForceModel FM;
GMAT FM.CentralBody = Earth;
GMAT FM.PrimaryBodies = {{Earth}};
GMAT FM.GravityField.Earth.PotentialFile = 'EGM96.cof';
GMAT FM.GravityField.Earth.Degree = {degree};
GMAT FM.GravityField.Earth.Order = 0;
GMAT FM.Drag.AtmosphereModel = {atmosphere};
GMAT FM.SRP = Off;
GMAT FM.RelativisticCorrection = Off;

Create Propagator Prop;
GMAT Prop.FM = FM;
GMAT Prop.Type = RungeKutta89;
GMAT Prop.InitialStepSize = 60;
GMAT Prop.Accuracy = 1e-13;
GMAT Prop.MinStep = 0;
GMAT Prop.MaxStep = 600;

Create ReportFile Report;
GMAT Report.Filename = '{output}';
GMAT Report.Precision = 16;
GMAT Report.WriteHeaders = true;
GMAT Report.LeftJustify = On;
GMAT Report.ZeroFill = Off;

Create Variable k tStop;

BeginMissionSequence;
Toggle Report Off;
Report Report Sat.ElapsedSecs Sat.EarthMJ2000Eq.X Sat.EarthMJ2000Eq.Y Sat.EarthMJ2000Eq.Z Sat.EarthMJ2000Eq.VX Sat.EarthMJ2000Eq.VY Sat.EarthMJ2000Eq.VZ;
For k = 1:1:{hours}
   tStop = k * 3600;
   Propagate Prop(Sat) {{Sat.ElapsedSecs = tStop}};
   Report Report Sat.ElapsedSecs Sat.EarthMJ2000Eq.X Sat.EarthMJ2000Eq.Y Sat.EarthMJ2000Eq.Z Sat.EarthMJ2000Eq.VX Sat.EarthMJ2000Eq.VY Sat.EarthMJ2000Eq.VZ;
EndFor;
"""


def main() -> None:
    FIXTURES.mkdir(parents=True, exist_ok=True)
    for name, sc in SCENARIOS.items():
        o = sc["orbit"]()
        x, y, z = o.r / 1e3
        vx, vy, vz = o.v / 1e3
        text = TEMPLATE.format(
            name=name, epoch=EPOCH_GMAT, x=x, y=y, z=z, vx=vx, vy=vy, vz=vz,
            degree=sc["degree"], atmosphere="Exponential" if sc["drag"] else "None",
            hours=sc["hours"], output=(FIXTURES / f"{name}.txt").as_posix(), **DRAG_SAT,
        )
        path = HERE / f"{name}.script"
        path.write_text(text, encoding="utf-8")
        print(f"작성: {path}")


if __name__ == "__main__":
    main()
