name: tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python: ["3.10", "3.11", "3.12", "3.13"]
        resolution: [highest]
        include:
          # Oldest dependency versions allowed by pyproject.toml
          - os: ubuntu-latest
            python: "3.10"
            resolution: lowest-direct
          - os: windows-latest
            python: "3.11"
            resolution: highest
    steps:
      - uses: actions/checkout@v5
      # With python-version, setup-uv creates and activates a virtual environment
      - uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python }}
      - name: Install
        run: uv pip install --resolution ${{ matrix.resolution }} ".[dev]" pytest-github-actions-annotate-failures
      - name: Test
        run: python -m pytest -q -rf
        env:
          MPLBACKEND: Agg
          PYTHONIOENCODING: utf-8
